import { Metadata } from "next";
import { getCurrentUser } from "@/lib/session";

import MainNavigation from "@/components/navigation/MainNavigation";
import Footer from "@/components/navigation/Footer";

export const metadata: Metadata = {
  title: "Crisanto Transient House - Amenities",
  description: "Generated by create next app",
};

const AmenitiesLayout = async ({ children }: { children: React.ReactNode }) => {
  const admin = await getCurrentUser();

  return (
    <main className="bg-[#fcf4e9]">
      <MainNavigation admin={admin} /> {children}
      <Footer />
    </main>
  );
};

export default AmenitiesLayout;
