// import { Metadata } from "next";

import MainNavigation from "@/components/navigation/MainNavigation";
import Footer from "@/components/navigation/Footer";

// export const metadata: Metadata = {
//   title: "Coastal Charm - Reservations",
//   description: "Generated by create next app",
// };

export default function FeedbackLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <MainNavigation />
      {children}
      <Footer />
    </main>
  );
}
