// import { Metadata } from "next";

import { MainNavigation, Footer } from "@/app/ui/navigation/navigation";

// export const metadata: Metadata = {
//   title: "Coastal Charm - Reservations",
//   description: "Generated by create next app",
// };

export default function ContactLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="bg-[#fcf4e9]">
      <MainNavigation /> {children}
      <Footer />
    </main>
  );
}
