// import { Metadata } from "next";

import AdminNavigation from "@/app/ui/navigations/admin-navigation";

// import Footer from "@/app/ui/navigations/footer";

// export const metadata: Metadata = {
//   title: "Coastal Charm - Reservations",
//   description: "Generated by create next app",
// };

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="bg-[#fcf4e9]">
      <AdminNavigation />
      {children}
    </main>
  );
}
